language: cpp
os:
  - windows

install:
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then choco install visualstudio2017-workload-vctools -y; fi

script:
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then ./code/build.bat; fi

